### ISSUE TITLE
What is the maximum data rate that this serial link can achieve

### ISSUE THREAD

**Issue by crossoverao** [pulp-platform/serial_link#3]
Hi guys,
  Could you please tell me what is the maximum data rate that this serial link can achieve? or in any of your previous projects, what was the highest data rate achieved by it?

**Comment by christian-lanius** [comment]
If you run the testbench, it reports the datarate at the end. You can play around with the parameters and see it scale, based on configuration. The theoretical upper bound would be 4xfin*axiwordsize (read master + write master + read slave + write slave). fin depends on your technology/FPGA. The DDR frequency depends on your IO cells, and might limit the value to a lower value.
Playing around with it, I got around ~80% of the maximum DDR is achieved according to the testbench (i.e. at 2MHz DDR and I use 3 lanes, single channel), I get 5Mbit/s single direction (maximum with 100% utilization of the DDR interface would be 6Mbit /s single direction).

**Comment by fischeti** [comment]
Hi,
As @christian-lanius already said, it depends on the configuration of the Serial Link:
* `NumChannels`: Number of independent physical channels each with their own source synchronous clock
* `NumLanes`: Number of wires per physical channel
* `I/O Frequency`: The serial link is meant to be used with standard IO cells, which limits the DDR frequency. 

So the maximum bandwidth is: 

$$ NumChannels \times NumLanes \times \times f_{IO} \times 2_{DDR} \times 2_{duplex}$$

So far we used the Serial Link in [Occamy](https://pulp-platform.org/occamy/), with two different configurations:
1. Single channel, 8 wires per channel, 125 MHz (expected): 4Gbps
1. 38 channels, 8 wires per channel, 125 MHz (expected): 152Gbps

**Comment by crossoverao** [comment]
Hi,
 @fischeti  @christian-lanius  thanks for your reply, it's very helpful. I’m interested in how fast speed that a single  standard IO cells can achieved. It is very surprised to know you can get 125MHz with Double-Data-Rate.  Thank you again!
